CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  age INT NOT NULL,
  salary NUMERIC(10,2) NOT NULL,
  birthday DATE NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS geo_items (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  location POINT NOT NULL,
  area GEOMETRY(POLYGON, 4326),
  created_at TIMESTAMP DEFAULT NOW()
);
